### ISSUE TITLE
Change aperture

### ISSUE THREAD

**Issue by ayozeah** [astrofelipe/tesseract#1]
Hello,

First of all, thank you very much for sharing your code with the community. I am trying to use it to obtain the TESS light curve of GK Per. I am having a  problem with the aperture. I am running the code as it is indicated ("python TIC ID Sector") and it works, but the default aperture is too big (it says that the aperture chosen is the number 5, containing 437 pixels). Is there any way to change it to a more reasonable aperture for this object?

Sorry for the inconvenience.

Cheers,
Ayoze

**Comment by astrofelipe** [comment]
Hello,

Are you using the default settings? Try using the "--circ" flag, which tries different circular apertures instead of the clustering algorithm that tesseract uses by default. I'll be adding the option to fix the radius of the circular aperture soon.

If the automatic circular apertures doesn't work, in the meanwhile you can try "--manualap aperturefile", where aperturefile contains the coordinates of each pixel you want to include in the aperture. The format is two columns, x and y, with the target at the center and 0,0 at bottom right (bottom left if not).

Good luck and thanks for the feedback!
Felipe

**Comment by astrofelipe** [comment]
Now you can specify the radius of the circular aperture using --circ and the radius of the aperture (eg, --circ 3). Previous behaviour (select based on best CDPP) can be accesed using "--circ 0"

**Comment by ayozeah** [comment]
Thank you so much Felipe! It worked perfectly :) 

Congratulations for the great tool.

Cheers,
Ayoze
